#!/usr/bin/env python3

from IP import IPPacket
import socket
from utils import get_local_ip
import threading
from scapy.all import *


from TCP import TCPPacket

CLIENT_PORT = 6969


def recv():
    recv_sock = socket.socket(socket.PF_PACKET, socket.SOCK_RAW, socket.htons(0x800))

    while True:
        raw_pkt, _ = recv_sock.recvfrom(2048)
        ip_pkt = IPPacket.from_bytes(raw_pkt=raw_pkt)
        if ip_pkt.protocol == socket.IPPROTO_TCP and ip_pkt.dst == get_local_ip():
            tcp_pkt = TCPPacket.from_bytes(ip_pkt=ip_pkt, raw_tcp_pkt=ip_pkt.data)
            if tcp_pkt.dst_port == CLIENT_PORT:
                print(tcp_pkt)


def send():
    send_sock = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_RAW)
    local_ip = get_local_ip()

    dst_host, dst_port = ("142.251.35.174", 80)

    tcp_pkt = TCPPacket(
        src_host=local_ip, src_port=CLIENT_PORT, dst_host=dst_host, dst_port=dst_port
    )
    tcp_pkt.seq_num = 3616486384
    tcp_pkt.syn = True
    tcp_pkt_raw = tcp_pkt.pack_fields()

    ip_pkt = IPPacket(src=local_ip, dst=dst_host, data=tcp_pkt_raw)
    ip_pkt_raw = ip_pkt.pack_fields()

    bytes_sent = send_sock.sendto(ip_pkt_raw, (dst_host, dst_port))
    assert len(ip_pkt_raw) == bytes_sent


if __name__ == "__main__":
    recv_thread = threading.Thread(target=recv)
    recv_thread.start()

    send_thread = threading.Thread(target=send)
    send_thread.start()
